config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'articles#index', as: :tag
  
  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_taggable
  
  def self.search(search)
    if search
      where("title ILIKE ?", "%#{search}%") 
    else
      where
    end
  end
  is_impressionable

  def comments
    Comment.where({ source_id: self.id, source_type: "Article" })
  end

end

app/models/comment.rb
class Comment < ApplicationRecord

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  impressionist :actions => [:show]
  #impressionist


  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    if params[:search]
      @articles = Article.search(params[:search])
      if @articles.blank?
        @articles = Article.tagged_with(params[:search])
      end

    elsif params[:tag]
      @articles = Article.tagged_with(params[:tag]) 
    end



    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)

  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    impressionist(@article) 

    if @article.impressionist_count == nil

      @article.page_view = 0
    else

      @article.page_view = @article.impressionist_count

    end

    @article.save
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    
    respond_to do |format|
      if params[:preview_button]
        format.html { render :new }
      else
        if @article.save
          #format.json { render :show, status: :created, location: @article }
          format.html { redirect_to @article}
          flash[:success] = "Article was successfully created."
        else
          format.html { render :new }
          #format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    
    @article = Article.find(params[:id])
    @article.attributes = article_params

    respond_to do |format|
      if params[:preview_button]
        format.html { render :edit }
      else
        if @article.save
          format.html { redirect_to @article}
          #format.json { render :show, status: :ok, location: @article }
          flash[:success] = "Article was successfully updated."
        else
          format.html { render :edit }
          #format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url}
      #format.json { head :no_content }
      flash[:alert] = "Article with id:#{@article.id} was successfully destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :tag_list)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comments = Comment.new
  end

  def create
    @articles  = Article.find(params[:article_id])
    @comments  = Comment.new(comment_params)
    respond_to do |format|
      format.html
      format.json
    end
    
    @comments.save

    redirect_to article_comments_path(@articles)
  end

  def show
    #@comments = Comment.where({:source_id => params[:source_id], :source_type => params[:source_type]})
  end

  def index
    @comments = Comment.where({:source_id => params[:article_id], :source_type => "Article"})
    respond_to do |format|
      format.html
      format.js
    end

  end

  
  private
    def comment_params
      params.require(:comment).permit(:name, :content, :source_type, :source_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.erb
<div class="row">
  <div class="col-sm-8">
    <div class="card-header">
       <ul class="nav nav-tabs card-header-tabs float-xs-left">
        <li class="nav-item">
          <%= link_to "Article", article_path(article), class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "View Comments (#{article.comments.size})", article_comments_path(article), class: "nav-link" %>
        </li>
      </ul>
    </div>

    <div class="card-block", style="display:inline;">
      <h4 class="card-title"><%= article.title %>  <span class="glyphicon glyphicon-eye-open" style="float:right"> <%= article.page_view %> </span></h4>
      <p class="card-text">  
        <p> 
          <small> Tags :
            <%= raw article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
          </small>
        </p>
      </p>
      <p class="card-text"> <%= @markdown.render(article.body).html_safe %> </p>    
    </div>

            
    <div class="card-footer">
      <%= link_to 'Show', article_path(article), class:'btn btn-info' %>
      <%= link_to 'Edit', edit_article_path(article), class:'btn btn-warning' %>
      <%= link_to 'Delete', article, method: :delete, data: {confirm: 'Are you sure?'}, class:'btn btn-danger' %>    
    </div>
  </div>
</div>

<br>

app/views/articles/_form.html.erb
<div class="row">
    <div class="col-sm-8">

    <%= form_for(article) do |f| %>
      <% if article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
          <% article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class:'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class:'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :tag_list, "Tags (Separated by comma)" %><br />
        <%= f.text_field :tag_list, class:'form-control' %>
      </div>


      <div class="actions">
        <%= f.submit class:'btn btn-primary' %>
        <%= button_tag(type: 'submit', class: "btn btn-link", :name => "preview_button") do %>
        Preview
        <% end %>
      </div>

      <br>

       <% if params[:preview_button] %>
         <%= @markdown.render(@article.body).html_safe %>
       <% end %>



    <% end %>
    <br>
    
  </div>
</div>
<br>

app/views/articles/edit.html.erb
<div class="container">
	<h1>Editing Article</h1>
	
	<%= render 'form', article: @article %>
	
	<%= link_to 'Show', @article %> |
	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<h2> Minh's sample blog </h2>

<nav class="navbar navbar-light bg-faded">
	<%= link_to 'https://github.com/minhhuynguyen91/prework_blog' do  %>
		<i class="fa fa-github" style="font-size:36px;color: Black;"></i>
	<% end %>

	<%= link_to 'https://plus.google.com/101254840748865913695' do  %>
		<i class="fa fa-google-plus-official" style="font-size:36px;color: Red;"></i>
	<% end %>

	<%= link_to 'https://www.facebook.com/huy.minh.coi' do  %>
		<i class="fa fa-facebook-official" style="font-size:36px;"></i>
	<% end %>

	<%= link_to 'https://vn.linkedin.com/in/minh-nguyen-b49a40105' do  %>
		<i class="fa fa-linkedin-square" style="font-size:36px;"></i>
	<% end %>


	<%= form_tag(articles_path, :method => "get") do %>
		<%= text_field_tag :search, params[:search], placeholder: 'Search title or tag name' %>
		<button type='submit', class='btn btn-info btn-sm'> 
			<span class="glyphicon glyphicon-search"></span> Search 
		</button>

	<% end %>
</nav>


<br>  


<br>


<% if @articles.blank? %>

  <h3> Sorry, there is no database </h3>
  
<% else %>

  <%= render @articles %>

<% end %>

<br>

<%= link_to 'New Article', new_article_path %>
</div>

app/views/articles/new.html.erb
<div class="container">
	<h1>New Article</h1>
	
	<%= render 'form', article: @article %>
	
	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-sm-8">
    <p>
      <h1> <%= @article.title %> </h1>
    </p>
    
    <p>
      
      <%= @markdown.render(@article.body).html_safe %>
    </p>
    
    <p>
      <strong> Tags: </strong> 
      <%= raw @article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
    </p>


    <p> ------------ </p> 
    <%= link_to 'Add new comment', '#modal-window', class:'btn btn-info', 'data-toggle' => 'modal' %>
    
    <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
             <h3 id="myModalLabel">Add comment</h3>
           </div>
           <div class="modal-body">
              <%= render 'comments/form', article: @article %>
           </div>
          <div class="modal-footer">
             <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
          </div>
        </div>
      </div>
    
    </div>

    <br>
    
    <%= link_to 'Edit', edit_article_path(@article) %> |
    <%= link_to 'Back', articles_path %>
    </div>
  </div>   
</div>

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-sm-8">

    <div class="card card-inverse" style="background-color: #333; border-color: #333;">
      <div class="card-block">
        <h3 class="card-title"><%= comment.name %></h3>
        <p class="card-text"> <%= comment.content %> </p>
      </div>
    </div>

  </div>
</div>
<br>

app/views/comments/_form.html.erb
<%= form_for Comment.new, url: article_comments_path(article) do |f| %>
  <%= f.label :'Name' %>
  <%= f.text_field :name, style: 'width: 300px;', class: 'form-control', placeholder: 'Enter your name' %>
  <%= f.hidden_field :source_id, value: article.id %>
  <%# <%= f.text_field :source_id, value: article.id %>
  <%= f.hidden_field :source_type, value: "Article" %>
  <br>
  <%= f.label :content %> 
  <%= f.text_area :content, style: 'width: 300px;', class: 'form-control', placeholder: 'Enter your comment' %>
  <br>
  <%= f.submit "Add comment", class: "btn btn-primary" %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.html.erb
<div class="container">

<h3> Comment section </h3>

<%= link_to 'Hide comments', '#', id: "comments-link", :remote => true %>

<div id='comments-section'>
	<div id="comments">
		<%= render @comments %>
	</div>	
</div>

<br>
<%= link_to 'Back', articles_path, class:'btn btn-info' %>

</div>

app/views/comments/index.js.erb
var showString 	 = document.getElementById("comments-link").innerHTML;
var toggleString = (showString == 'Show comments' ? 'Hide comments' : 'Show comments');

document.getElementById("comments-link").innerHTML = toggleString;

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/_notify.html.erb
<% if flash[:success] %>
	
<div class="alert alert-success">
  <%= flash[:success] %>
</div>

<% elsif flash[:alert] %>
	
<div class="alert alert-danger">
  <%= flash[:alert] %>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  </head>
    
  <body>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
      <%= link_to "Blog", articles_path , id: "blog_header" %>
    </nav>
    <%= render 'layouts/notify' %>    
    <%= yield %>
  </body>
</html>